set_property SRC_FILE_INFO {cfile:{D:/Studies/10_Projects/Digital Design Projects/Verilog/1_AND_Gate/1_AND_Gate.srcs/constrs_1/new/AND.xdc} rfile:../../../1_AND_Gate.srcs/constrs_1/new/AND.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports a]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports b]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports y]
